"""empty message

Revision ID: 3b4e164c0601
Revises: 997fdc824a2b
Create Date: 2019-05-11 15:00:46.569690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4e164c0601'
down_revision = '997fdc824a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('sub_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_submission_sub_time'), 'submission', ['sub_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_sub_time'), table_name='submission')
    op.drop_column('submission', 'sub_time')
    # ### end Alembic commands ###
