"""empty message

Revision ID: 4bcd2679832f
Revises: d2fd90c13538
Create Date: 2019-05-11 14:50:31.479331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcd2679832f'
down_revision = 'd2fd90c13538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_hash'), 'submission', ['hash'], unique=True)
    op.create_index(op.f('ix_submission_name'), 'submission', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_name'), table_name='submission')
    op.drop_index(op.f('ix_submission_hash'), table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
