"""empty message

Revision ID: 94281f0e0cef
Revises: b7f4b0cb7dea
Create Date: 2019-06-03 20:55:09.098726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94281f0e0cef'
down_revision = 'b7f4b0cb7dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_created'), 'block', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_block_created'), table_name='block')
    op.drop_table('block')
    # ### end Alembic commands ###
