"""empty message

Revision ID: 997fdc824a2b
Revises: 4bcd2679832f
Create Date: 2019-05-11 14:59:00.883347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997fdc824a2b'
down_revision = '4bcd2679832f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_submission_team_id'), 'submission', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_team_id'), table_name='submission')
    op.drop_column('submission', 'team_id')
    # ### end Alembic commands ###
