"""empty message

Revision ID: d2fd90c13538
Revises: 
Create Date: 2019-05-10 13:14:28.620909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fd90c13538'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('private_id', sa.Text(), nullable=True),
    sa.Column('reg_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_email'), 'team', ['email'], unique=True)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=True)
    op.create_index(op.f('ix_team_private_id'), 'team', ['private_id'], unique=True)
    op.create_index(op.f('ix_team_reg_time'), 'team', ['reg_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_reg_time'), table_name='team')
    op.drop_index(op.f('ix_team_private_id'), table_name='team')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_email'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
